App_Login/urls.py
from django.urls import path
from App_Login import views

app_name = "App_Login"

urlpatterns=[
    path('signup/',views.signUp, name='sign_up'),
    path('login/',views.login_page, name='login'),
    path('edit/',views.edit_profile, name='edit'),
    path('logout/',views.logout_user, name='logout'),
    path('profile/',views.profile, name="profile"),
    path('user/<username>/',views.user , name="user"),
    path('follow/<username>/', views.follow , name="follow"),
    path('unfollow/<username>/', views.unfollow , name="unfollow"),
    ]

App_Posts/urls.py
from django.urls import path
from App_Posts import views

app_name = "App_Posts"

urlpatterns = [
    path('', views.home, name="home"),
    path('liked/<pk>/', views.liked, name="liked"),
    path('unliked/<pk>/', views.unliked, name="unliked"),


]

My_Social_Project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns
from App_Posts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("App_Login.urls")),
    path('post/',include("App_Posts.urls")),
    path('',views.home, name="home"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />

    <title>{% block title_block %} Social {% endblock title_block %}</title>

    {% block css_block %}
    
    {% endblock css_block %}

  </head>
  <body>

<div class="container" style="padding-top:20px">

{% block body_block %}{% endblock body_block %}

</div>






    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/navbar.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />


    <title>{% block title_block %} Social {% endblock title_block %}</title>

    {% block css_block %} {% endblock css_block %}
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'App_Posts:home' %}">Home</a>
        </li>
        &nbsp; &nbsp; &nbsp; &nbsp;
        <form class="form-inline" method="GET">
          <input
          name = "search"
            class="form-control mr-sm-2"
            type="text"
            placeholder="Search"
          />
          <button class="btn btn-success" type="submit">Search</button>
        </form>

        <li class="nav-item">
          <a class="nav-link active" href="{% url 'App_Login:logout' %}"
            >Logout</a
          >
        </li>
        <li class="nav-item">
          {% if user.user_profile.profile_pic %}

          <a class="nav-link active" href="{% url 'App_Login:profile' %}">
            <img
              src="/media/{{user.user_profile.profile_pic}}"
              width="40px"
              alt="image"
              class="rounded-circle"
              height="40px"
            />
          </a>

          {% else %}
          <a class="nav-link active" href="{% url 'App_Login:profile' %}">
            <img
              src="/media/dp.jpg"
              width="40px"
              alt="image"
              class="rounded-circle"
              height="40px"
          /></a>

          {% endif %}
        </li>
      </ul>
    </nav>

    <div class="container" style="padding-top: 20px">
      {% block body_block %}{% endblock body_block %}
    </div>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>

    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
      integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
      integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
      crossorigin="anonymous"
    ></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  </body>
</html>